#!/bin/bash
set -e

DISPLAY_MANAGER="$(systemctl show -p Id --value display-manager)"
case "${DISPLAY_MANAGER%.service}" in
    plasmalogin) CONF_FILE="/etc/plasmalogin.conf";;
esac

# Don't do anything if system is using unsupported display manager
[[ -z "$CONF_FILE" ]] && exit 0

# Session, gamescope or plasma
SESSION="${1:-gamescope-session.desktop}"

if [[ "${DISPLAY_MANAGER%.service}" == "plasmalogin" ]]; then
    # Modify only the Session parameter while keeping the rest of the file intact
    if grep -q "^\[Autologin\]" "$CONF_FILE" 2>/dev/null; then
        sed -i "s/^Session=.*/Session=$SESSION/" "$CONF_FILE"
    else
        cat >> "$CONF_FILE" <<EOF

[Autologin]
User=deck
Session=$SESSION
Relogin=true
EOF
    fi
else
    if [[ ! -d "$(dirname "$CONF_FILE")" ]]; then
        mkdir -p "$(dirname "$CONF_FILE")"
    fi
    cat <<EOF > "$CONF_FILE"
[Autologin]
Session=$SESSION
EOF
fi
